framework:
  rate_limiter:
    company_route:
      policy: 'fixed_window'
      limit: 5
      interval: '1 minute'
    company_route_id:
      policy: 'fixed_window'
      limit: 5
      interval: '1 minute'