controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

company_route:
    path: /company
    controller: App\Controller\CompanyController::index

company_route_id:
    path: /company/id/{id}
    controller: App\Controller\CompanyController::show

company_route_inrange:
    path: /company/inrange
    controller: App\Controller\CompanyController::inrange





